spring:
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册


  mybatis:
    mapper-locations:
      - classpath:com/**/dao/*.xml
      - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

redis:
  key:
    prefix:
      verificationCode: "admin:verificationCode"
    expire:
      verificationCode: 60 # 验证码超时时间

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /user/login
      - /user/register
      - /user/updatePassword
      - /user/getVerificationCode
      - /user/veificationCodelogin
      - /minio/upload



  minio:
    endpoint: http://192.168.3.101:9090 #MinIO服务所在地址
    bucketName: mall #存储桶名称
    accessKey: minioadmin #访问的key
    secretKey: minioadmin #访问的秘钥


logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称